version: "3.9"
services:

  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /tmp/devops/data:/data
      - /tmp/devops/letsencrypt:/etc/letsencrypt

      
  user-example:
    image: ${USER_CONTAINER}
    ports:
      - "8080:8080"
    volumes:
      - user-example-logs:/usr/local/tomcat/logs

volumes:
  user-example-logs: {}
