name: Test-Workflow

on:
  push:
    branches:
      - test
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: 'Login to docker with GHCR'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build with Maven
        working-directory: ./experimental/user-project/user-example/
        run: | 
          mvn -B --update-snapshots package -P packageAsDocker
          docker build ./docker -f ./docker/Dockerfile -t ghcr.io/${{ github.repository_owner }}/user-example:v0.0.1
          docker push ghcr.io/${{ github.repository_owner }}/user-example:v0.0.1
          
      - name: "Upload docker-compose to Azure"
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: '${{ secrets.AZURE_USERNAME }}'
          server: '${{ secrets.AZURE_HOSTNAME }}'
          ssh_private_key: '${{ secrets.AZURE_KEY }}'
          local_path: './experimental/user-project/user-example/docker/docker-compose.yml'
          remote_path: '/tmp/docker-compose.yml'
          
      - name: "Run Compose on Azure"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_HOSTNAME }}
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.AZURE_KEY }}
          port: 22 
          script: |
            docker stop $(docker ps -a -q)
            USER_CONTAINER=ghcr.io/${{ github.repository_owner }}/user-example:v0.0.1 docker-compose -f /tmp/docker-compose.yml up -d 
